
%% participant info
participant = struct();

if ~parameters.flag_debug
    participant.id = nan;
    while isnan(participant.id)
        participant.id = str2double(input('  Id : ','s'));
    end
    participant.age  = input('  Age:      ','s');
    participant.sex  = input('  Sex:      ','s');
    participant.hand = input('  Hand:     ','s');
else
    participant.id   = nan;
    participant.age  = '';
    participant.sex  = '';
    participant.hand = '';
end

% structure
participant.structure = cell(2,12);
switch (participant.id)
    case  1, participant.structure = strcat('fruits',filesep(),reshape({'watermelon','peach','coconut','olive','mango','pineapple','pear','grapefruit','cherry','avocado','guava','melon','lime','star','plum','strawberry','orange','banana','grapes','pomegranate','figs','apple','lemon','kiwii'},[2,12]));
    case  2, participant.structure = strcat('fruits',filesep(),reshape({'lemon','banana','melon','pear','cherry','orange','pomegranate','guava','grapes','star','mango','pineapple','grapefruit','apple','olive','plum','peach','coconut','lime','watermelon','figs','kiwii','strawberry','avocado'},[2,12]));
    case  3, participant.structure = strcat('fruits',filesep(),reshape({'lemon','lime','orange','melon','pomegranate','avocado','guava','apple','mango','cherry','grapefruit','figs','star','kiwii','grapes','coconut','peach','plum','banana','olive','strawberry','watermelon','pear','pineapple'},[2,12]));
    case  4, participant.structure = strcat('fruits',filesep(),reshape({'peach','kiwii','coconut','apple','guava','avocado','pomegranate','cherry','grapes','plum','pear','lime','figs','watermelon','banana','olive','lemon','orange','grapefruit','melon','star','pineapple','strawberry','mango'},[2,12]));
    case  5, participant.structure = strcat('fruits',filesep(),reshape({'cherry','watermelon','lime','orange','plum','figs','grapefruit','guava','apple','banana','strawberry','melon','lemon','kiwii','pineapple','peach','mango','pomegranate','olive','avocado','star','pear','coconut','grapes'},[2,12]));
    case  6, participant.structure = strcat('fruits',filesep(),reshape({'avocado','banana','orange','coconut','pomegranate','peach','pear','figs','melon','apple','lime','grapefruit','cherry','grapes','watermelon','mango','guava','kiwii','plum','strawberry','pineapple','star','olive','lemon'},[2,12]));
    case  7, participant.structure = strcat('fruits',filesep(),reshape({'avocado','guava','mango','apple','cherry','watermelon','pomegranate','lime','star','melon','pineapple','olive','grapes','pear','banana','coconut','orange','lemon','kiwii','peach','plum','grapefruit','strawberry','figs'},[2,12]));
    case  8, participant.structure = strcat('fruits',filesep(),reshape({'olive','strawberry','melon','kiwii','orange','cherry','pear','peach','grapefruit','plum','avocado','mango','coconut','lime','pineapple','banana','lemon','guava','apple','figs','star','watermelon','pomegranate','grapes'},[2,12]));
    case  9, participant.structure = strcat('fruits',filesep(),reshape({'apple','plum','kiwii','pomegranate','olive','melon','lime','strawberry','guava','pear','lemon','figs','banana','cherry','grapefruit','avocado','peach','star','watermelon','pineapple','grapes','coconut','mango','orange'},[2,12]));
    case 10, participant.structure = strcat('fruits',filesep(),reshape({'lime','apple','olive','pear','lemon','mango','coconut','figs','orange','grapefruit','banana','watermelon','guava','peach','pomegranate','kiwii','grapes','cherry','avocado','star','plum','strawberry','pineapple','melon'},[2,12]));
    case 11, participant.structure = strcat('fruits',filesep(),reshape({'guava','banana','avocado','pineapple','grapes','coconut','grapefruit','apple','figs','olive','orange','strawberry','star','pear','mango','plum','kiwii','lime','melon','peach','lemon','cherry','pomegranate','watermelon'},[2,12]));
    case 12, participant.structure = strcat('fruits',filesep(),reshape({'guava','pear','banana','olive','lemon','grapefruit','peach','lime','plum','mango','coconut','kiwii','watermelon','figs','pomegranate','apple','strawberry','avocado','star','melon','grapes','orange','cherry','pineapple'},[2,12]));
    case 13, participant.structure = strcat('fruits',filesep(),reshape({'mango','pineapple','lime','grapefruit','kiwii','coconut','cherry','orange','pear','star','melon','olive','guava','lemon','avocado','plum','figs','grapes','strawberry','peach','banana','apple','pomegranate','watermelon'},[2,12]));
    case 14, participant.structure = strcat('fruits',filesep(),reshape({'pear','pomegranate','olive','star','lemon','cherry','banana','avocado','peach','coconut','apple','mango','kiwii','lime','figs','grapefruit','orange','strawberry','guava','melon','pineapple','watermelon','grapes','plum'},[2,12]));
    case 15, participant.structure = strcat('fruits',filesep(),reshape({'coconut','olive','pear','watermelon','lemon','grapefruit','guava','pineapple','apple','mango','star','avocado','strawberry','pomegranate','grapes','melon','orange','banana','kiwii','lime','figs','plum','cherry','peach'},[2,12]));
    case 16, participant.structure = strcat('fruits',filesep(),reshape({'melon','watermelon','pineapple','apple','kiwii','lemon','star','mango','guava','banana','pomegranate','cherry','orange','peach','figs','grapes','avocado','strawberry','olive','lime','coconut','plum','grapefruit','pear'},[2,12]));
    case 17, participant.structure = strcat('fruits',filesep(),reshape({'kiwii','plum','melon','pineapple','apple','star','figs','peach','grapes','lemon','watermelon','mango','olive','cherry','pear','orange','lime','grapefruit','pomegranate','banana','strawberry','coconut','guava','avocado'},[2,12]));
    case 18, participant.structure = strcat('fruits',filesep(),reshape({'pomegranate','strawberry','orange','olive','grapefruit','cherry','guava','melon','grapes','kiwii','apple','plum','pear','figs','lemon','watermelon','banana','peach','avocado','mango','pineapple','star','coconut','lime'},[2,12]));
    case 19, participant.structure = strcat('fruits',filesep(),reshape({'olive','grapes','guava','kiwii','grapefruit','watermelon','plum','pomegranate','star','coconut','mango','banana','orange','cherry','pear','melon','avocado','lime','figs','apple','lemon','pineapple','strawberry','peach'},[2,12]));
    case 20, participant.structure = strcat('fruits',filesep(),reshape({'plum','strawberry','lemon','watermelon','cherry','lime','apple','orange','grapes','kiwii','peach','avocado','olive','pomegranate','star','pineapple','guava','melon','pear','grapefruit','banana','mango','figs','coconut'},[2,12]));
    case 21, participant.structure = strcat('fruits',filesep(),reshape({'plum','pineapple','olive','guava','grapefruit','watermelon','pear','cherry','avocado','strawberry','peach','orange','apple','star','lime','melon','kiwii','figs','lemon','pomegranate','coconut','banana','grapes','mango'},[2,12]));
    case 22, participant.structure = strcat('fruits',filesep(),reshape({'pomegranate','coconut','star','olive','avocado','grapes','kiwii','figs','pineapple','lime','orange','guava','melon','strawberry','mango','pear','lemon','banana','apple','cherry','grapefruit','plum','peach','watermelon'},[2,12]));
    case 23, participant.structure = strcat('fruits',filesep(),reshape({'pineapple','plum','pomegranate','peach','watermelon','cherry','kiwii','melon','coconut','lime','avocado','orange','star','olive','guava','grapes','figs','banana','apple','grapefruit','strawberry','mango','pear','lemon'},[2,12]));
    case 24, participant.structure = strcat('fruits',filesep(),reshape({'lime','strawberry','melon','figs','pomegranate','cherry','watermelon','avocado','guava','pineapple','olive','orange','coconut','pear','kiwii','banana','lemon','star','apple','mango','grapes','grapefruit','peach','plum'},[2,12]));
    case 25, participant.structure = strcat('fruits',filesep(),reshape({'apple','grapes','lemon','banana','olive','lime','peach','strawberry','melon','pear','mango','coconut','kiwii','avocado','plum','orange','pineapple','cherry','figs','guava','pomegranate','grapefruit','watermelon','star'},[2,12]));
    case 26, participant.structure = strcat('fruits',filesep(),reshape({'banana','cherry','orange','apple','star','pomegranate','lime','lemon','figs','coconut','grapes','avocado','pineapple','melon','peach','olive','mango','guava','grapefruit','plum','watermelon','strawberry','pear','kiwii'},[2,12]));
    case 27, participant.structure = strcat('fruits',filesep(),reshape({'pear','banana','olive','star','strawberry','apple','lime','grapes','orange','mango','kiwii','watermelon','peach','figs','grapefruit','coconut','plum','lemon','avocado','guava','pineapple','pomegranate','cherry','melon'},[2,12]));
    case 28, participant.structure = strcat('fruits',filesep(),reshape({'star','coconut','pineapple','orange','cherry','plum','figs','pear','banana','grapes','peach','guava','lemon','grapefruit','pomegranate','avocado','kiwii','strawberry','apple','olive','melon','lime','mango','watermelon'},[2,12]));
    case 29, participant.structure = strcat('fruits',filesep(),reshape({'avocado','pomegranate','melon','pineapple','strawberry','figs','peach','banana','apple','grapes','plum','lime','olive','kiwii','star','grapefruit','watermelon','pear','orange','guava','lemon','mango','cherry','coconut'},[2,12]));
    case 30, participant.structure = strcat('fruits',filesep(),reshape({'orange','mango','star','pear','watermelon','figs','cherry','coconut','kiwii','pineapple','strawberry','peach','banana','guava','grapes','lime','olive','plum','apple','grapefruit','melon','avocado','lemon','pomegranate'},[2,12]));
    case 31, participant.structure = strcat('fruits',filesep(),reshape({'pineapple','apple','kiwii','strawberry','grapes','banana','coconut','figs','watermelon','avocado','pomegranate','grapefruit','mango','peach','plum','olive','orange','pear','cherry','guava','lemon','lime','star','melon'},[2,12]));
    case 32, participant.structure = strcat('fruits',filesep(),reshape({'apple','strawberry','pomegranate','star','olive','mango','grapefruit','plum','peach','orange','pineapple','melon','kiwii','banana','lime','watermelon','coconut','pear','lemon','cherry','guava','figs','grapes','avocado'},[2,12]));
    case 33, participant.structure = strcat('fruits',filesep(),reshape({'pear','olive','watermelon','grapefruit','pomegranate','mango','banana','cherry','grapes','lemon','guava','strawberry','kiwii','lime','figs','apple','orange','star','avocado','peach','coconut','melon','plum','pineapple'},[2,12]));
    case 34, participant.structure = strcat('fruits',filesep(),reshape({'olive','lime','melon','orange','figs','guava','mango','plum','grapes','peach','kiwii','avocado','pear','grapefruit','strawberry','pineapple','coconut','star','lemon','apple','cherry','pomegranate','watermelon','banana'},[2,12]));
    case 35, participant.structure = strcat('fruits',filesep(),reshape({'peach','watermelon','lime','apple','star','grapes','plum','olive','melon','mango','lemon','pear','avocado','guava','coconut','grapefruit','kiwii','banana','cherry','pineapple','orange','strawberry','figs','pomegranate'},[2,12]));
    case 36, participant.structure = strcat('fruits',filesep(),reshape({'figs','banana','peach','grapes','lemon','melon','strawberry','watermelon','pear','apple','avocado','pineapple','pomegranate','coconut','guava','lime','cherry','plum','mango','kiwii','grapefruit','star','orange','olive'},[2,12]));
    case 37, participant.structure = strcat('fruits',filesep(),reshape({'grapes','coconut','lime','strawberry','peach','pineapple','mango','plum','apple','star','grapefruit','cherry','watermelon','guava','lemon','avocado','orange','pomegranate','figs','olive','pear','banana','kiwii','melon'},[2,12]));
    case 38, participant.structure = strcat('fruits',filesep(),reshape({'apple','plum','mango','orange','pineapple','banana','avocado','pomegranate','pear','lemon','star','cherry','strawberry','watermelon','grapes','olive','guava','lime','melon','kiwii','figs','coconut','grapefruit','peach'},[2,12]));
    case 39, participant.structure = strcat('fruits',filesep(),reshape({'kiwii','peach','figs','pineapple','coconut','star','grapes','guava','lime','cherry','grapefruit','apple','banana','pomegranate','orange','strawberry','pear','lemon','avocado','mango','watermelon','olive','melon','plum'},[2,12]));
    case 40, participant.structure = strcat('fruits',filesep(),reshape({'strawberry','grapefruit','coconut','plum','grapes','figs','avocado','star','mango','cherry','apple','olive','peach','pomegranate','lemon','watermelon','guava','kiwii','pear','pineapple','orange','lime','banana','melon'},[2,12]));
    otherwise % default case, also for debug
             participant.structure = strcat('fruits',filesep(),reshape({'star','cherry','apple','banana','watermelon','grapes','plum','mango','lemon','strawberry','peach','melon','figs','olive','pineapple','kiwii','grapefruit','guava','avocado','pear','coconut','pomegranate','orange','lime'},[2,12]));
end